import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "rgb(var(--ma-bg) / <alpha-value>)",
        surface: "rgb(var(--ma-surface) / <alpha-value>)",
        "surface-muted": "rgb(var(--ma-surface-muted) / <alpha-value>)",
        ink: "rgb(var(--ma-ink) / <alpha-value>)",
        "ink-soft": "rgb(var(--ma-muted) / <alpha-value>)",
        line: "rgb(var(--ma-line) / <alpha-value>)",
        accent: "rgb(var(--ma-accent) / <alpha-value>)",
        "accent-strong": "rgb(var(--ma-accent-strong) / <alpha-value>)",
        "accent-soft": "rgb(var(--ma-accent-soft) / <alpha-value>)",
        ok: "rgb(var(--ma-ok) / <alpha-value>)",
        warn: "rgb(var(--ma-warn) / <alpha-value>)",
        danger: "rgb(var(--ma-danger) / <alpha-value>)",
        night: "rgb(var(--ma-night) / <alpha-value>)",
        "night-card": "rgb(var(--ma-night-card) / <alpha-value>)",
        // Google Stitch design tokens
        primary: "#005c55",
        "primary-container": "#0f766e",
        "on-primary": "#ffffff",
        "on-primary-container": "#a3faef",
        "primary-fixed": "#9cf2e8",
        "primary-fixed-dim": "#80d5cb",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#00504a",
        "inverse-primary": "#80d5cb",
        secondary: "#2b6954",
        "secondary-container": "#adedd3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#306d58",
        "secondary-fixed": "#b0f0d6",
        "secondary-fixed-dim": "#95d3ba",
        "on-secondary-fixed": "#002117",
        "on-secondary-fixed-variant": "#0b513d",
        tertiary: "#7d4200",
        "tertiary-container": "#a15600",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffe6d5",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-bright": "#fcf9f4",
        "surface-dim": "#dcdad5",
        "surface-variant": "#e5e2dd",
        "surface-container": "#f0ede9",
        "surface-container-low": "#f6f3ee",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ebe8e3",
        "surface-container-highest": "#e5e2dd",
        "surface-tint": "#006a63",
        "on-surface": "#1c1c19",
        "on-surface-variant": "#3e4947",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f3f0eb",
        "on-background": "#1c1c19",
        outline: "#6e7977",
        "outline-variant": "#bdc9c6",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      spacing: {
        "container-margin": "24px",
        unit: "8px",
        "touch-target-min": "44px",
        "stack-gap": "24px",
        gutter: "16px",
      },
      fontSize: {
        "button-text": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-lg": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      fontFamily: {
        sans: [
          "var(--font-inter)",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
      },
      boxShadow: {
        soft: "0 1px 2px rgb(28 25 23 / 0.04), 0 4px 16px rgb(28 25 23 / 0.06)",
        lift: "0 2px 4px rgb(28 25 23 / 0.05), 0 12px 32px rgb(28 25 23 / 0.10)",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.97)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.55" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.45s cubic-bezier(0.22, 1, 0.36, 1) both",
        "fade-in": "fade-in 0.3s ease-out both",
        "scale-in": "scale-in 0.35s cubic-bezier(0.22, 1, 0.36, 1) both",
        "pulse-soft": "pulse-soft 2.2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
