import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        canvas: "rgb(var(--ma-bg) / <alpha-value>)",
        surface: "rgb(var(--ma-surface) / <alpha-value>)",
        "surface-muted": "rgb(var(--ma-surface-muted) / <alpha-value>)",
        ink: "rgb(var(--ma-ink) / <alpha-value>)",
        "ink-soft": "rgb(var(--ma-muted) / <alpha-value>)",
        line: "rgb(var(--ma-line) / <alpha-value>)",
        accent: "rgb(var(--ma-accent) / <alpha-value>)",
        "accent-strong": "rgb(var(--ma-accent-strong) / <alpha-value>)",
        "accent-soft": "rgb(var(--ma-accent-soft) / <alpha-value>)",
        ok: "rgb(var(--ma-ok) / <alpha-value>)",
        warn: "rgb(var(--ma-warn) / <alpha-value>)",
        danger: "rgb(var(--ma-danger) / <alpha-value>)",
        night: "rgb(var(--ma-night) / <alpha-value>)",
        "night-card": "rgb(var(--ma-night-card) / <alpha-value>)",
        // Material-3 palette (landing, footer, license). Backed by CSS
        // variables so a single `.dark` override recolors every page.
        primary: "rgb(var(--m3-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--m3-primary-container) / <alpha-value>)",
        "on-primary": "rgb(var(--m3-on-primary) / <alpha-value>)",
        "on-primary-container": "rgb(var(--m3-on-primary-container) / <alpha-value>)",
        "primary-fixed": "rgb(var(--m3-primary-fixed) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--m3-primary-fixed-dim) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--m3-on-primary-fixed) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--m3-on-primary-fixed-variant) / <alpha-value>)",
        "inverse-primary": "rgb(var(--m3-inverse-primary) / <alpha-value>)",
        secondary: "rgb(var(--m3-secondary) / <alpha-value>)",
        "secondary-container": "rgb(var(--m3-secondary-container) / <alpha-value>)",
        "on-secondary": "rgb(var(--m3-on-secondary) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--m3-on-secondary-container) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--m3-secondary-fixed) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--m3-secondary-fixed-dim) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--m3-on-secondary-fixed) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--m3-on-secondary-fixed-variant) / <alpha-value>)",
        tertiary: "rgb(var(--m3-tertiary) / <alpha-value>)",
        "tertiary-container": "rgb(var(--m3-tertiary-container) / <alpha-value>)",
        "on-tertiary": "rgb(var(--m3-on-tertiary) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--m3-on-tertiary-container) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--m3-tertiary-fixed) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--m3-tertiary-fixed-dim) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--m3-on-tertiary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--m3-on-tertiary-fixed-variant) / <alpha-value>)",
        "surface-bright": "rgb(var(--m3-surface-bright) / <alpha-value>)",
        "surface-dim": "rgb(var(--m3-surface-dim) / <alpha-value>)",
        "surface-variant": "rgb(var(--m3-surface-variant) / <alpha-value>)",
        "surface-container": "rgb(var(--m3-surface-container) / <alpha-value>)",
        "surface-container-low": "rgb(var(--m3-surface-container-low) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--m3-surface-container-lowest) / <alpha-value>)",
        "surface-container-high": "rgb(var(--m3-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--m3-surface-container-highest) / <alpha-value>)",
        "surface-tint": "rgb(var(--m3-surface-tint) / <alpha-value>)",
        "on-surface": "rgb(var(--m3-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--m3-on-surface-variant) / <alpha-value>)",
        "inverse-surface": "rgb(var(--m3-inverse-surface) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--m3-inverse-on-surface) / <alpha-value>)",
        "on-background": "rgb(var(--m3-on-background) / <alpha-value>)",
        outline: "rgb(var(--m3-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--m3-outline-variant) / <alpha-value>)",
        error: "rgb(var(--m3-error) / <alpha-value>)",
        "error-container": "rgb(var(--m3-error-container) / <alpha-value>)",
        "on-error": "rgb(var(--m3-on-error) / <alpha-value>)",
        "on-error-container": "rgb(var(--m3-on-error-container) / <alpha-value>)",
      },
      spacing: {
        "container-margin": "24px",
        unit: "8px",
        "touch-target-min": "44px",
        "stack-gap": "24px",
        gutter: "16px",
      },
      fontSize: {
        "button-text": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-lg": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      fontFamily: {
        sans: [
          "var(--font-inter)",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
      },
      boxShadow: {
        soft: "0 1px 2px rgb(28 25 23 / 0.04), 0 4px 16px rgb(28 25 23 / 0.06)",
        lift: "0 2px 4px rgb(28 25 23 / 0.05), 0 12px 32px rgb(28 25 23 / 0.10)",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.97)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.55" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.45s cubic-bezier(0.22, 1, 0.36, 1) both",
        "fade-in": "fade-in 0.3s ease-out both",
        "scale-in": "scale-in 0.35s cubic-bezier(0.22, 1, 0.36, 1) both",
        "pulse-soft": "pulse-soft 2.2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
