import {
  Bell,
  BookUser,
  Boxes,
  Clock,
  Drum,
  Eye,
  Footprints,
  Grid3x3,
  Images,
  IndianRupee,
  Landmark,
  Layers,
  LayoutGrid,
  ListOrdered,
  Music,
  Palette,
  Search,
  ShoppingBasket,
  Smile,
  SpellCheck,
  Sun,
  Crosshair,
  Target,
  Shapes,
  Zap,
} from "lucide-react";
import type { GameId } from "@/lib/games/types";

/** Shared icon mapping so play hub and host route stay consistent. */
export const GAME_ICONS: Record<GameId, React.ComponentType<{ className?: string }>> = {
  faces: Images,
  names: BookUser,
  memorylane: Landmark,
  market: ShoppingBasket,
  pairs: LayoutGrid,
  melody: Music,
  drums: Drum,
  soundmatch: Bell,
  stroop: Palette,
  trail: Footprints,
  routine: Sun,
  loom: Layers,
  oddone: Search,
  sortit: Boxes,
  bazaar: IndianRupee,
  spatial: Eye,
  sequence: Grid3x3,
  clock: Clock,
  spot: Eye,
  wordrecall: BookUser,
  follow: Zap,
  shadow: Sun,
  reaction: Zap,
  wordbuilder: SpellCheck,
  category: Shapes,
  emotion: Smile,
  target: Target,
  order: ListOrdered,
};

export const GAME_ROUTES: Record<GameId, string> = {
  faces: "/play/faces",
  names: "/play/names",
  memorylane: "/play/memorylane",
  market: "/play/market",
  pairs: "/play/pairs",
  melody: "/play/melody",
  drums: "/play/drums",
  soundmatch: "/play/soundmatch",
  stroop: "/play/stroop",
  trail: "/play/trail",
  routine: "/play/routine",
  loom: "/play/loom",
  oddone: "/play/oddone",
  sortit: "/play/sortit",
  bazaar: "/play/bazaar",
  spatial: "/play/spatial",
  sequence: "/play/sequence",
  clock: "/play/clock",
  spot: "/play/spot",
  wordrecall: "/play/wordrecall",
  follow: "/play/follow",
  shadow: "/play/shadow",
  reaction: "/play/reaction",
  wordbuilder: "/play/wordbuilder",
  category: "/play/category",
  emotion: "/play/emotion",
  target: "/play/target",
  order: "/play/order",
};

export const GAME_TITLES: Record<GameId, string> = {
  faces: "Who Is In The Photo?",
  names: "Remembering Names",
  memorylane: "Memory Lane",
  market: "Market Basket",
  pairs: "Card Pairs",
  melody: "Repeat the Tune",
  drums: "Festival Drums",
  soundmatch: "Sound Match",
  stroop: "Color Trap",
  trail: "Number Trail",
  routine: "Morning Routine",
  loom: "Pattern Loom",
  oddone: "Odd One Out",
  sortit: "Sorting Station",
  bazaar: "Bazaar Maths",
  spatial: "Where Did I Keep It?",
  sequence: "Pattern Sequence",
  clock: "Telling the Time",
  spot: "Spot the Change",
  wordrecall: "Word Recall",
  follow: "Follow the Lights",
  shadow: "Shadow Match",
  reaction: "Quick Tap",
  wordbuilder: "Word Builder",
  category: "Category Sort",
  emotion: "Feelings Match",
  target: "Find the Target",
  order: "Put in Order",
};

export interface GameCategory {
  id: "remember" | "focus" | "think" | "find";
  /** Locale phrase key for the category heading. */
  titleKey: "catRemember" | "catFocus" | "catThink" | "catFind";
  /** Locale phrase key for the one-line category description. */
  blurbKey: "catRememberBlurb" | "catFocusBlurb" | "catThinkBlurb" | "catFindBlurb";
}

/** Hub sections, in display order. */
export const GAME_CATEGORIES: readonly GameCategory[] = [
  { id: "remember", titleKey: "catRemember", blurbKey: "catRememberBlurb" },
  { id: "focus", titleKey: "catFocus", blurbKey: "catFocusBlurb" },
  { id: "think", titleKey: "catThink", blurbKey: "catThinkBlurb" },
  { id: "find", titleKey: "catFind", blurbKey: "catFindBlurb" },
];
